### ISSUE TITLE
Want few changes if possible

### ISSUE THREAD

**Issue by umerirfan26** [arnavchhokra/CalendarApp_Swift#1]
Hi. Thank you for this wonderful app. I want to know how can we make month, year in dropDown or pickerView.

**Comment by arnavchhokra** [comment]
Sure, just add  two Stack View drop down(one for month and other for year) view instead of the MonthLbL and make the month dropdown include values of the Month array. Also change Calendar.current.component(.month, from Date()) accordingly.

**Comment by umerirfan26** [comment]
Calendar.current.component(.month, from Date())
I’m having trouble changing this part. Can you please send me another ViewController with dropDown options.
